import aws_cdk.aws_glue_alpha as glue
from shared_components.buckets import (
    data_baker_results_bucket,
    ee_data_cache_production,
    pollingstations_private_data,
)
from shared_components.databases import dc_data_baker
from shared_components.models import BaseQuery, GlueTable

addressbase_cleaned_raw = GlueTable(
    table_name="addressbase_cleaned_raw",
    description="Addressbase table as produced for loading into WDIV",
    bucket=pollingstations_private_data,
    s3_prefix="addressbase/2025-01-20/addressbase_cleaned/",
    database=dc_data_baker,
    data_format=glue.DataFormat.CSV,
    columns={
        "uprn": glue.Schema.STRING,
        "address": glue.Schema.STRING,
        "postcode": glue.Schema.STRING,
        "location": glue.Schema.STRING,
        "address_type": glue.Schema.STRING,
    },
)

addressbase_partitioned = GlueTable(
    table_name="addressbase_partitioned",
    description="Addressbase table partitioned by first letter of postcode. With latitude and longitude columns",
    s3_prefix="addressbase/{dc_environment}/addressbase_partitioned/",
    bucket=pollingstations_private_data,
    database=dc_data_baker,
    data_format=glue.DataFormat.PARQUET,
    columns={
        "outcode": glue.Schema.STRING,
        "uprn": glue.Schema.STRING,
        "address": glue.Schema.STRING,
        "postcode": glue.Schema.STRING,
        "longitude": glue.Schema.DOUBLE,
        "latitude": glue.Schema.DOUBLE,
        "addressbase_source": glue.Schema.STRING,
    },
    partition_keys=[
        glue.Column(
            name="first_letter",
            type=glue.Schema.STRING,
        )
    ],
    depends_on=[addressbase_cleaned_raw],
    populated_with=BaseQuery(
        name="partition-addressbase-cleaned.sql",
        context={"from_table": addressbase_cleaned_raw.table_name},
    ),
)

current_ballots = GlueTable(
    table_name="current_ballots",
    description="CSV in S3 generated by EE, contains each current ballot and the WKT of the geography",
    s3_prefix="ballots-with-wkt/",
    bucket=ee_data_cache_production,
    database=dc_data_baker,
    data_format=glue.DataFormat.CSV,
    columns={
        "election_id": glue.Schema.STRING,
        "division_id": glue.Schema.STRING,
        "geometry": glue.Schema.STRING,
        "source_table": glue.Schema.STRING,
    },
)

current_ballots_joined_to_address_base = GlueTable(
    table_name="current_ballots_joined_to_address_base",
    description="A list of current ballots per UPRN",
    s3_prefix="addressbase/{dc_environment}/current_ballots_joined_to_address_base/",
    bucket=pollingstations_private_data,
    database=dc_data_baker,
    data_format=glue.DataFormat.PARQUET,
    columns={
        "uprn": glue.Schema.STRING,
        "address": glue.Schema.STRING,
        "postcode": glue.Schema.STRING,
        "addressbase_source": glue.Schema.STRING,
        "ballot_ids": glue.Schema.array(
            input_string="string", is_primitive=True
        ),
        "first_letter": glue.Schema.STRING,
    },
    populated_with=BaseQuery(
        name="uprn-to-ballots-first-letter.sql",
        context={"from_table": current_ballots.table_name},
    ),
)


current_boundary_changes = GlueTable(
    table_name="current_boundary_changes",
    description="A list of boundary changes with a WKT",
    s3_prefix="current_boundary_reviews-with-wkt/",
    bucket=data_baker_results_bucket,
    database=dc_data_baker,
    data_format=glue.DataFormat.CSV,
    columns={
        "review_id": glue.Schema.STRING,
        "slug": glue.Schema.STRING,
        "status": glue.Schema.STRING,
        "latest_event": glue.Schema.STRING,
        "consultation_url": glue.Schema.STRING,
        "legislation_title": glue.Schema.STRING,
        "effective_date": glue.Schema.STRING,
        "created": glue.Schema.STRING,
        "modified": glue.Schema.STRING,
        "common_name": glue.Schema.STRING,
        "official_name": glue.Schema.STRING,
        "organisation_gss": glue.Schema.STRING,
        "organisation_boundary_wkt": glue.Schema.STRING,
    },
)

current_boundary_changes_joined_to_address_base = GlueTable(
    table_name="current_boundary_changes_joined_to_address_base",
    description="A list of current boundary changes per UPRN",
    s3_prefix="current_boundary_reviews-joined-to-addressbase/",
    bucket=data_baker_results_bucket,
    database=dc_data_baker,
    data_format=glue.DataFormat.PARQUET,
    columns={
        "uprn": glue.Schema.STRING,
        "address": glue.Schema.STRING,
        "postcode": glue.Schema.STRING,
        "addressbase_source": glue.Schema.STRING,
        "boundary_review_ids": glue.Schema.array(
            input_string="string", is_primitive=True
        ),
        "first_letter": glue.Schema.STRING,
    },
    populated_with=BaseQuery(
        name="current-boundary-changes-to-addressbase.sql",
        context={"from_table": current_boundary_changes.table_name},
    ),
)
